apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ladesa-ro-api-db-pvc
  labels:
    app: ladesa-ro-api
spec:
  storageClassName: ""
  volumeName: ladesa-ro-api-db-development-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
