apiVersion: v1
kind: PersistentVolume
metadata:
  name: sso-db-pv
  namespace: default
  labels:
    app: registry
spec:
  volumeMode: Filesystem
  hostPath:
    path: /mnt/storage/sso/db/data
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: default
    name: sso-db-pvc
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: x-ladesa-infra-host
              operator: In
              values:
                - "yes"
