apiVersion: v1
kind: PersistentVolume
metadata:
  name: ladesa-ro-sso-db-pv
  labels:
    app: ladesa-ro-sso
spec:
  volumeMode: Filesystem
  hostPath:
    path: /dev/null
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  claimRef:
    name: ladesa-ro-sso-db-pvc
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: x-ladesa-infra-host
              operator: In
              values:
                - "yes"
