apiVersion: apps/v1
kind: Deployment
metadata:
  name: ladesa-ro-sso
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: ladesa-ro-sso
          image: "ghcr.io/ladesa-ro/auth:development"
