name: Deploy simple resource
description: Deploys a simple kubernetes resource into the cluster

inputs:
  enabled:
    description: "set true for enabled and false for disabled"
  path:
    description: "path to yml/yaml file"
  namespace:
    description: "namespace"

runs:
  using: composite

  steps:
    - shell: bash
      env:
        RESOURCE_PATH: ${{ inputs.path }}
        RESOURCE_ENABLED: ${{ inputs.enabled }}
        RESOURCE_NAMESPACE: ${{ inputs.namespace }}
      run: |
        EXTRA_OPTS=""

        if [ ! -z "${RESOURCE_NAMESPACE}" ]; then
          EXTRA_OPTS+=" -n ${RESOURCE_NAMESPACE}";
        fi

        if [ "${RESOURCE_ENABLED}" == "true" ]; then
          kubectl apply -f ${RESOURCE_PATH} ${EXTRA_OPTS};
        else
          kubectl delete -f ${RESOURCE_PATH} ${EXTRA_OPTS} --ignore-not-found=true;
        fi
