version: 0.1
log:
  accesslog:
    disabled: true
  level: debug
  formatter: text
  fields:
    service: registry
#     environment: staging
#   hooks:
#     - type: mail
#       disabled: true
#       levels:
#         - panic
#       options:
#         smtp:
#           addr: mail.example.com:25
#           username: mailuser
#           password: password
#           insecure: true
#         from: sender@example.com
#         to:
#           - errors@example.com
# loglevel: debug # deprecated: use "log"
storage:
  filesystem:
    rootdirectory: /data
    maxthreads: 100
  delete:
    enabled: true
#   cache:
#     blobdescriptor: redis
#     blobdescriptorsize: 10000
#   maintenance:
#     uploadpurging:
#       enabled: true
#       age: 168h
#       interval: 24h
#       dryrun: false
#     readonly:
#       enabled: false
auth:
  token:
    autoredirect: true
    realm: https://sso.ladesa.com.br/realms/registry/protocol/docker-v2/auth
    service: docker-registry
    issuer: https://sso.ladesa.com.br/realms/registry
    rootcertbundle: /opt/certs/localhost_trust_chain.pem
    signingalgorithms:
      - EdDSA
      - HS256
http:
  addr: 0.0.0.0:5000
#   prefix: /my/nested/registry/
#   host: https://myregistryaddress.org:5000
#   secret: asecretforlocaldevelopment
#   relativeurls: false
#   draintimeout: 60s
#   tls:
#     certificate: /path/to/x509/public
#     key: /path/to/x509/private
#     clientcas:
#       - /path/to/ca.pem
#       - /path/to/another/ca.pem
#     letsencrypt:
#       cachefile: /path/to/cache-file
#       email: emailused@letsencrypt.com
#       hosts: [myregistryaddress.org]
#       directoryurl: https://acme-v02.api.letsencrypt.org/directory
#   debug:
#     addr: localhost:5001
#     prometheus:
#       enabled: true
#       path: /metrics
#   headers:
#     X-Content-Type-Options: [nosniff]
#   http2:
#     disabled: false
#   h2c:
#     enabled: false
# notifications:
#   events:
#     includereferences: true
#   endpoints:
#     - name: alistener
#       disabled: false
#       url: https://my.listener.com/event
#       headers: <http.Header>
#       timeout: 1s
#       threshold: 10
#       backoff: 1s
#       ignoredmediatypes:
#         - application/octet-stream
#       ignore:
#         mediatypes:
#            - application/octet-stream
#         actions:
#            - pull
# redis:
#   addr: localhost:6379
#   password: asecret
#   db: 0
#   dialtimeout: 10ms
#   readtimeout: 10ms
#   writetimeout: 10ms
#   pool:
#     maxidle: 16
#     maxactive: 64
#     idletimeout: 300s
#   tls:
#     enabled: false
# health:
#   storagedriver:
#     enabled: true
#     interval: 10s
#     threshold: 3
#   file:
#     - file: /path/to/checked/file
#       interval: 10s
#   http:
#     - uri: http://server.to.check/must/return/200
#       headers:
#         Authorization: [Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ==]
#       statuscode: 200
#       timeout: 3s
#       interval: 10s
#       threshold: 3
#   tcp:
#     - addr: redis-server.domain.com:6379
#       timeout: 3s
#       interval: 10s
#       threshold: 3
# proxy:
#   remoteurl: https://registry-1.docker.io
#   username: [username]
#   password: [password]
#   ttl: 168h
# validation:
#   manifests:
#     urls:
#       allow:
#         - ^https?://([^/]+\.)*example\.com/
#       deny:
#         - ^https?://www\.example\.com/
#     indexes:
#       platforms: List
#       platformlist:
#       - architecture: amd64
#         os: linux
