apiVersion: apps/v1
kind: Deployment
metadata:
  name: ladesaro-api
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ladesaro-api
      spec:
        containers:
          - name: mycontainer
            image: nginx:1.14.2
            ports:
              - containerPort: 80
        envFrom:
          - configMapRef:
              name: ladesaro-api-configmap
        resources:
          requests:
            memory: "500MiB"
            cpu: "50m" # 500milliCPUsj (1/2 CPU)
          limits:
            memory: "2Gb"
            cpu: "100m"
