apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-certs-pv
  namespace: default
  labels:
    app: registry
spec:
  volumeMode: Filesystem
  hostPath:
    path: /mnt/storage/registry/certs
  capacity:
    storage: 100Mi
  accessModes:
    - ReadOnlyMany
  claimRef:
    namespace: default
    name: registry-certs-pvc
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: x-ladesa-infra-host
              operator: In
              values:
                - "yes"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-certs-pvc
  namespace: default
  labels:
    app: registry
spec:
  storageClassName: manual
  volumeName: registry-certs-pv
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
