apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ladesa-ro-issuer-production
  namespace: cert-manager

spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory

    email: gabrielrodantunes@gmail.com

    privateKeySecretRef:
      name: ladesa-ro-issuer-production

    solvers:
      - http01:
          ingress:
            class: nginx
