apiVersion: apps/v1
kind: Deployment
metadata:
  name: ladesa-ro-sso
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ladesa-ro-sso
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        name: ladesa-ro-sso
    spec:
      containers:
        - name: ladesa-ro-sso
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 8080
          envFrom:
            - secretRef:
                name: ladesa-ro-sso-config
          resources:
            requests:
              cpu: "50m"
              memory: "1Gi"
            limits:
              memory: "2Gi"
              cpu: "2"
