kind: Deployment
apiVersion: apps/v1
metadata:
  name: hello-world
  namespace: ${APP_NAMESPACE}
  labels:
    app: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world
          image: traefik/whoami:latest
          ports:
            - name: web
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: ${APP_NAMESPACE}
spec:
  ports:
    - name: web
      port: 8080
      targetPort: web
  selector:
    app: hello-world
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world-ingress
  namespace: ${APP_NAMESPACE}
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-world
                port:
                  name: web
