ACTION_LOG_ARCHIVE_LOCATION: default
ACTION_LOG_ARCHIVE_PATH: /var/log/quay
ACTION_LOG_ROTATION_THRESHOLD: 30m
AUTHENTICATION_TYPE: AppToken
AVATAR_KIND: gravatar
# this defaults to true, but allows you to omit the
# user/org part of a container namespace, and have it interpreted as "library".
# For example: `quay.io/library/python` will be equivalent to `quay.io/python`.
FEATURE_LIBRARY_SUPPORT: true
# allows users to rename account
FEATURE_USER_RENAME: true
BUILDLOGS_REDIS:
  host: <redis_host>
  password: <redis_password>
  port: 6379
DB_CONNECTION_ARGS:
  keepalives: 0
  keepalivescount: 0
  keepalivesidle: 0
  keepalivesinterval: 0
  sslcompression: 0
  tcpusertimeout: 0
DB_URI: postgresql://<db_user>:<db_password>@<db_host>/<db_database>
DEFAULT_TAG_EXPIRATION: 1w
DISTRIBUTED_STORAGE_CONFIG:
  default:
    - LocalStorage
    - storage_path: /datastorage/registry
DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS: []
DISTRIBUTED_STORAGE_PREFERENCE:
  - default
EXTERNAL_TLS_TERMINATION: true
FEATURE_ACTION_LOG_ROTATION: true
FEATURE_ANONYMOUS_ACCESS: true
FEATURE_APP_SPECIFIC_TOKENS: true
FEATURE_BITBUCKET_BUILD: false
FEATURE_BLACKLISTED_EMAILS: false
FEATURE_BUILD_SUPPORT: true
FEATURE_CHANGE_TAG_EXPIRATION: true
FEATURE_DIRECT_LOGIN: false
FEATURE_EXTENDED_REPOSITORY_NAMES: true
FEATURE_FIPS: false
FEATURE_GITHUB_BUILD: false
FEATURE_GITHUB_LOGIN: false
FEATURE_GITLAB_BUILD: false
FEATURE_GOOGLE_LOGIN: false
FEATURE_INVITE_ONLY_USER_CREATION: false
FEATURE_MAILING: false
FEATURE_NONSUPERUSER_TEAM_SYNCING_SETUP: false
FEATURE_PARTIAL_USER_AUTOCOMPLETE: true
FEATURE_PROXY_STORAGE: true
FEATURE_REPO_MIRROR: false
FEATURE_SECURITY_NOTIFICATIONS: false
FEATURE_SECURITY_SCANNER: false
FEATURE_STORAGE_REPLICATION: false
FEATURE_TEAM_SYNCING: false
FEATURE_USER_CREATION: false
FEATURE_USER_LAST_ACCESSED: true
FEATURE_USER_LOG_ACCESS: false
FEATURE_USER_METADATA: false
FEATURE_USERNAME_CONFIRMATION: true
FRESH_LOGIN_TIMEOUT: 10m
GITHUB_LOGIN_CONFIG: {}
GITHUB_TRIGGER_CONFIG: {}
GITLAB_TRIGGER_KIND: {}
LADESA_LOGIN_CONFIG:
  CLIENT_ID: <ladesa_sso_client_id>
  CLIENT_SECRET: <ladesa_sso_client_secret>
  OIDC_SERVER: https://<ladesa_sso_url>/realms/<ladesa_sso_realm>/
  SERVICE_NAME: Ladesa Registry Account
LDAP_ALLOW_INSECURE_FALLBACK: false
LDAP_EMAIL_ATTR: mail
LDAP_UID_ATTR: uid
LDAP_URI: ldap://localhost
LOGS_MODEL: database
LOGS_MODEL_CONFIG: {}
MAIL_DEFAULT_SENDER: support@quay.io
MAIL_PORT: 587
MAIL_USE_AUTH: false
MAIL_USE_TLS: false
PREFERRED_URL_SCHEME: https
REGISTRY_TITLE: <registry_title>
REGISTRY_TITLE_SHORT: <registry_title_short>
REPO_MIRROR_INTERVAL: 30
REPO_MIRROR_TLS_VERIFY: true
SEARCH_MAX_RESULT_PAGE_COUNT: 10
SEARCH_RESULTS_PER_PAGE: 10
SECURITY_SCANNER_INDEXING_INTERVAL: 30
SERVER_HOSTNAME: <registry_hostname>
SUPER_USERS:
  - <registry_superuser>
TAG_EXPIRATION_OPTIONS:
  - 0s
  - 1d
  - 1w
  - 2w
  - 4w
TEAM_RESYNC_STALE_TIME: 30m
USER_EVENTS_REDIS:
  host: <redis_host>
  password: <redis_password>
  port: 6379
USER_RECOVERY_TOKEN_LIFETIME: 30m
