apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config-map
  namespace: default
data:
  REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
  REGISTRY_HTTP_ADDR: 0.0.0.0:5000
  # REGISTRY_HTTP_TLS_CERTIFICATE: /opt/certs/localhost.crt
  # REGISTRY_HTTP_TLS_KEY: /opt/certs/localhost.key
  REGISTRY_AUTH_TOKEN_REALM: https://sso.ladesa.com.br/realms/registry/protocol/docker-v2/auth
  REGISTRY_AUTH_TOKEN_SERVICE: docker-registry
  REGISTRY_AUTH_TOKEN_ISSUER: https://sso.ladesa.com.br/realms/registry
  REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /opt/certs/localhost_trust_chain.pem
  REGISTRY_STORAGE_DELETE_ENABLED: "true"
