apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: quay-ingress
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: PathPrefix(`/`)
      services:
        - name: quay
          namespace: default
          port: web
