apiVersion: apps/v1
kind: Deployment
metadata:
  name: ladesa-ro-api
spec:
  replicas: 2
  selector:
    matchLabels:
      name: ladesa-ro-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        name: ladesa-ro-api
    spec:
      volumes:
        - name: uploaded-data
          persistentVolumeClaim:
            claimName: ladesa-ro-api-uploaded-pvc
      containers:
        - name: ladesa-ro-api
          image: "nginx:1"
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 80
          envFrom:
            - secretRef:
                name: ladesa-ro-api-config
          volumeMounts:
            - name: uploaded-data
              mountPath: /var/lib/ladesa-ro-api/uploaded
          resources:
            requests:
              cpu: "50m"
              memory: "1Gi"
            limits:
              memory: "2Gi"
              cpu: "2"
