name: "Continuous Deployment"

on:
  push:
    branches: main
    paths:
      - .github/workflows/cd.yml
      - .github/actions/deploy-simple-resource/**/*
      - resources/**/*

  workflow_dispatch:

jobs:
  cd:
    runs-on: deploy
    steps:
      - uses: actions/checkout@v4

      - name: "resources/base/certificates/development"
        uses: ./.github/actions/deploy-simple-resource
        with:
          enabled: ${{ vars.ENABLE_CERT_DEVELOPMENT }}
          path: ./resources/base/certificates/development/issuer.yaml

      - name: "resources/base/certificates/production"
        uses: ./.github/actions/deploy-simple-resource
        with:
          enabled: ${{ vars.ENABLE_CERT_PRODUCTION }}
          path: ./resources/base/certificates/production/issuer.yaml

      - name: "resources/base/storages/sso/db/development"
        uses: ./.github/actions/deploy-kustomize-resource
        with:
          enabled: ${{ vars.ENABLE_STORAGE_SSO_DB_DEVELOPMENT }}
          path: ./resources/base/storages/sso/db/development

      - name: "resources/base/storages/sso/db/production"
        uses: ./.github/actions/deploy-kustomize-resource
        with:
          enabled: ${{ vars.ENABLE_STORAGE_SSO_DB_PRODUCTION }}
          path: ./resources/base/storages/sso/db/production

      - name: "resources/base/storages/api/db/development"
        uses: ./.github/actions/deploy-kustomize-resource
        with:
          enabled: ${{ vars.ENABLE_STORAGE_API_DB_DEVELOPMENT }}
          path: ./resources/base/storages/api/db/development

      - name: "resources/base/storages/api/db/production"
        uses: ./.github/actions/deploy-kustomize-resource
        with:
          enabled: ${{ vars.ENABLE_STORAGE_API_DB_PRODUCTION }}
          path: ./resources/base/storages/api/db/production

      - name: "resources/base/storages/api/uploaded/development"
        uses: ./.github/actions/deploy-kustomize-resource
        with:
          enabled: ${{ vars.ENABLE_STORAGE_API_UPLOADED_DEVELOPMENT }}
          path: ./resources/base/storages/api/uploaded/development

      - name: "resources/base/storages/api/uploaded/production"
        uses: ./.github/actions/deploy-kustomize-resource
        with:
          enabled: ${{ vars.ENABLE_STORAGE_API_UPLOADED_PRODUCTION }}
          path: ./resources/base/storages/api/uploaded/production

      - name: "resources/base/storages/registry/certs/development"
        uses: ./.github/actions/deploy-kustomize-resource
        with:
          enabled: ${{ vars.ENABLE_STORAGE_REGISTRY_CERTS_PRODUCTION }}
          path: ./resources/base/storages/registry/certs/production

      - name: "resources/base/storages/registry/artifacts/production"
        uses: ./.github/actions/deploy-kustomize-resource
        with:
          enabled: ${{ vars.ENABLE_STORAGE_REGISTRY_ARTIFACTS_PRODUCTION }}
          path: ./resources/base/storages/registry/artifacts/production