name: "Continuous Deployment"

on:
  push:
    branches: main
    paths:
      - .github/workflows/cd.yml
      - resources/**/*

  workflow_dispatch:

jobs:
  cd:
    runs-on: deploy
    steps:
      - uses: actions/checkout@v4

      - name: "resources/base/certificates/development"
        uses: ./.github/actions/deploy-simple-resource
        with:
          enabled: ${{ vars.ENABLE_CERT_DEVELOPMENT }}
          path: ./resources/base/certificates/development/issuer.yaml
