name: Deploy Services

on:
  workflow_dispatch:

jobs:
  deploy-to-control-plane:
    name: Run deploy script
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            TMP_GH_REPOSITORY_URL=${{ github.repositoryUrl }}

            LADESA_REPOSITORY=${TMP_GH_REPOSITORY_URL/git:/https:}
            LADESA_REPOSITORY_BRANCH=${{ github.ref_name }}
            LADESA_LOCAL_PATH=/tmp/ladesa-ro/infra/repo

            if [ ! -d ${LADESA_LOCAL_PATH}/.git ]; then
              rm -rf ${LADESA_LOCAL_PATH};
              git clone ${LADESA_REPOSITORY} ${LADESA_LOCAL_PATH};
            fi

            cd ${LADESA_LOCAL_PATH};
            git remote set-url origin ${LADESA_REPOSITORY};

            git fetch -p;
            git clean -f -x;
            git reset --hard origin/${LADESA_REPOSITORY_BRANCH};

            ./deploy.sh;
