name: Get pods

on:
  workflow_dispatch:

jobs:
  deploy-to-control-plane:
    name: Deploy to Control Plane
    runs-on: self-hosted

    steps:
    - name: executing remote ssh commands
      run: kubectl get pods
