name: Deploy Services

on:
  workflow_dispatch:

jobs:
  copy-files-to-control-plane:
    name: Copy files to the control plane machine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          rm: true
          source: "*,!.git"
          target: /tmp/ladesa-ro/infra/repo

  deploy-to-control-plane:
    name: Run deploy script
    runs-on: ubuntu-latest
    needs: copy-files-to-control-plane
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            kubectl get pods;
            cd /tmp/ladesa-ro/infra/repo;
            ./deploy.sh;
