name: "Maintenance - System Updates"

on:
  schedule:
    - cron: "30 3 * * 6,0-2"
  workflow_dispatch:
  push:
    paths: 
      - '.github/workflows/system-updates.yml'

jobs:
  system-update:
    runs-on:
      group: maintenance
    steps:
      - run: |
          topgrade --yes --skip-notify
