name: "Maintenance — System Updates"

on:
  workflow_dispatch:
  schedule:
    - cron: "30 3 * * 6,0-2"
  push:
    paths: 
      - '.github/workflows/system-updates.yml'

concurrency:
  group: maintenance
  cancel-in-progress: false

jobs:
  system-update:
    runs-on:
      group: maintenance
    
    steps:
      - uses: actions/checkout@v4

      - run: bash ./update-system.sh
        working-directory: utils/system-updates
