name: "Maintenance - Garbage Collection"

on:
  schedule:
    - cron: "10-40/23 * * * *"
  workflow_dispatch:
  push:
      paths: 
        - '.github/workflows/system-updates.yml'
jobs:
  system-cleanup:
    runs-on:
      group: maintenance
    steps:
      - uses: actions/checkout@v4
      - run: bash ./utils/collect-garbage.sh
