apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ladesa-ro-sso-db-pvc
  labels:
    app: ladesa-ro-sso
spec:
  storageClassName: ""
  volumeName: ladesa-ro-sso-db-development-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
